"""add_timestamps_to_order_items

Revision ID: 1d2081ae3860
Revises: bdd84b411617
Create Date: 2025-12-03 17:00:46.307338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d2081ae3860'
down_revision: Union[str, Sequence[str], None] = 'bdd84b411617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sell_sessions_id'), table_name='sell_sessions')
    op.drop_index(op.f('ix_sell_sessions_session_id'), table_name='sell_sessions')
    op.drop_index(op.f('ix_sell_sessions_user_phone'), table_name='sell_sessions')
    op.drop_table('sell_sessions')
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_trade_in_sessions_session_type'), table_name='trade_in_sessions')
    op.drop_column('trade_in_sessions', 'session_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_in_sessions', sa.Column('session_type', sa.VARCHAR(length=20), server_default=sa.text("'trade_in'::character varying"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_trade_in_sessions_session_type'), 'trade_in_sessions', ['session_type'], unique=False)
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    op.create_table('sell_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('product_model', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('retail_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('price_source', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('images_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('s3_keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('condition_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('condition_grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issues_found', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('overall_assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category_questions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition_responses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usage_age', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sell_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_offer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_offer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_offer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('condition_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valuation_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('offer_decision', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('redemption_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pickup_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('product_collected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sell_sessions_pkey'))
    )
    op.create_index(op.f('ix_sell_sessions_user_phone'), 'sell_sessions', ['user_phone'], unique=False)
    op.create_index(op.f('ix_sell_sessions_session_id'), 'sell_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sell_sessions_id'), 'sell_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
