"""redesign_trade_in_session_to_single_table

Revision ID: 6afdf88dd3d7
Revises: 9cdbdd8e5603
Create Date: 2025-10-26 21:06:15.620347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afdf88dd3d7'
down_revision: Union[str, Sequence[str], None] = '9cdbdd8e5603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_in_sessions', sa.Column('images_uploaded', sa.Boolean(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('s3_keys', sa.JSON(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('condition_score', sa.Float(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('condition_grade', sa.String(length=50), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('issues_found', sa.JSON(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('overall_assessment', sa.Text(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('trade_in_value', sa.Float(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('final_offer', sa.Float(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('condition_factor', sa.Float(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('market_factor', sa.Float(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('valuation_reasoning', sa.Text(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('offer_decision', sa.String(length=50), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('redemption_method', sa.String(length=50), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('pickup_address', sa.String(length=500), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('store_credit_balance', sa.Float(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('product_collected', sa.Boolean(), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('trade_in_sessions', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('trade_in_sessions', 'product_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('trade_in_sessions', 'retail_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_in_sessions', 'retail_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trade_in_sessions', 'product_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('trade_in_sessions', 'end_time')
    op.drop_column('trade_in_sessions', 'start_time')
    op.drop_column('trade_in_sessions', 'product_collected')
    op.drop_column('trade_in_sessions', 'store_credit_balance')
    op.drop_column('trade_in_sessions', 'contact_phone')
    op.drop_column('trade_in_sessions', 'pickup_address')
    op.drop_column('trade_in_sessions', 'redemption_method')
    op.drop_column('trade_in_sessions', 'offer_decision')
    op.drop_column('trade_in_sessions', 'valuation_reasoning')
    op.drop_column('trade_in_sessions', 'market_factor')
    op.drop_column('trade_in_sessions', 'condition_factor')
    op.drop_column('trade_in_sessions', 'final_offer')
    op.drop_column('trade_in_sessions', 'trade_in_value')
    op.drop_column('trade_in_sessions', 'overall_assessment')
    op.drop_column('trade_in_sessions', 'issues_found')
    op.drop_column('trade_in_sessions', 'condition_grade')
    op.drop_column('trade_in_sessions', 'condition_score')
    op.drop_column('trade_in_sessions', 's3_keys')
    op.drop_column('trade_in_sessions', 'image_urls')
    op.drop_column('trade_in_sessions', 'images_uploaded')
    # ### end Alembic commands ###
