"""Add trade-in session tables

Revision ID: 7793bfa6a037
Revises: 8bd18fad3110
Create Date: 2025-10-26 01:26:18.560018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7793bfa6a037'
down_revision: Union[str, Sequence[str], None] = '8bd18fad3110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop dependent tables first
    op.drop_table('trade_in_credits')
    op.drop_table('trade_in_images')
    op.drop_table('trade_ins')
    
    # Drop column from orders
    op.drop_column('orders', 'trade_in_credit_applied')
    
    # Create new trade-in session tables
    op.create_table('trade_in_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_model', sa.String(length=200), nullable=True),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('price_source', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_in_sessions_id'), 'trade_in_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_trade_in_sessions_session_id'), 'trade_in_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_trade_in_sessions_user_phone'), 'trade_in_sessions', ['user_phone'], unique=False)
    
    op.create_table('trade_in_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trade_in_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_in_images_id'), 'trade_in_images', ['id'], unique=False)
    
    op.create_table('trade_in_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('condition_score', sa.Float(), nullable=False),
    sa.Column('condition_grade', sa.String(length=50), nullable=False),
    sa.Column('issues_found', sa.JSON(), nullable=True),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trade_in_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_in_assessments_id'), 'trade_in_assessments', ['id'], unique=False)
    
    op.create_table('trade_in_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('trade_in_value', sa.Float(), nullable=False),
    sa.Column('final_offer', sa.Float(), nullable=False),
    sa.Column('condition_factor', sa.Float(), nullable=False),
    sa.Column('market_factor', sa.Float(), nullable=False),
    sa.Column('valuation_reasoning', sa.Text(), nullable=True),
    sa.Column('user_decision', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trade_in_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_in_valuations_id'), 'trade_in_valuations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_in_images', sa.Column('trade_in_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trade_in_images', sa.Column('image_key', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trade_in_images', type_='foreignkey')
    op.create_foreign_key(op.f('trade_in_images_trade_in_id_fkey'), 'trade_in_images', 'trade_ins', ['trade_in_id'], ['id'])
    op.alter_column('trade_in_images', 'image_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('trade_in_images', 's3_key')
    op.drop_column('trade_in_images', 'session_id')
    op.add_column('orders', sa.Column('trade_in_credit_applied', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('trade_in_credits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trade_in_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remaining_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PARTIALLY_USED', 'FULLY_USED', 'EXPIRED', 'CANCELLED', name='creditstatus'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trade_in_id'], ['trade_ins.id'], name=op.f('trade_in_credits_trade_in_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('trade_in_credits_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_in_credits_pkey'))
    )
    op.create_index(op.f('ix_trade_in_credits_id'), 'trade_in_credits', ['id'], unique=False)
    op.create_table('trade_ins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('device_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('condition_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('assessed_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('offer_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ASSESSED', 'OFFERED', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='tradeinstatus'), autoincrement=False, nullable=True),
    sa.Column('trade_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pickup_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pickup_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('trade_ins_order_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('trade_ins_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_ins_pkey'))
    )
    op.create_index(op.f('ix_trade_ins_id'), 'trade_ins', ['id'], unique=False)
    # ### end Alembic commands ###
