"""add_trade_in_decisions_table

Revision ID: 8f845336eada
Revises: 9dc97e79e85f
Create Date: 2025-10-26 02:21:13.914539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f845336eada'
down_revision: Union[str, Sequence[str], None] = '9dc97e79e85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_in_credits_id'), table_name='trade_in_credits')
    op.drop_table('trade_in_credits')
    op.drop_index(op.f('ix_trade_ins_id'), table_name='trade_ins')
    op.drop_table('trade_ins')
    op.drop_column('orders', 'trade_in_credit_applied')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trade_in_credit_applied', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('trade_ins',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('trade_ins_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('device_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('condition_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('assessed_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('offer_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ASSESSED', 'OFFERED', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='tradeinstatus'), autoincrement=False, nullable=True),
    sa.Column('trade_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pickup_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pickup_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='trade_ins_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='trade_ins_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trade_ins_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_trade_ins_id'), 'trade_ins', ['id'], unique=False)
    op.create_table('trade_in_credits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trade_in_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remaining_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PARTIALLY_USED', 'FULLY_USED', 'EXPIRED', 'CANCELLED', name='creditstatus'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trade_in_id'], ['trade_ins.id'], name=op.f('trade_in_credits_trade_in_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('trade_in_credits_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_in_credits_pkey'))
    )
    op.create_index(op.f('ix_trade_in_credits_id'), 'trade_in_credits', ['id'], unique=False)
    # ### end Alembic commands ###
