"""add_redemption_fields_to_trade_in_valuations

Revision ID: 9cdbdd8e5603
Revises: 8f845336eada
Create Date: 2025-10-26 02:32:48.784724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cdbdd8e5603'
down_revision: Union[str, Sequence[str], None] = '8f845336eada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_in_decisions_id'), table_name='trade_in_decisions')
    op.drop_table('trade_in_decisions')
    op.add_column('trade_in_valuations', sa.Column('redemption_method', sa.String(length=50), nullable=True))
    op.add_column('trade_in_valuations', sa.Column('pickup_address', sa.String(length=500), nullable=True))
    op.add_column('trade_in_valuations', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('trade_in_valuations', sa.Column('store_credit_balance', sa.Float(), nullable=True))
    op.add_column('trade_in_valuations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_in_valuations', 'updated_at')
    op.drop_column('trade_in_valuations', 'store_credit_balance')
    op.drop_column('trade_in_valuations', 'contact_phone')
    op.drop_column('trade_in_valuations', 'pickup_address')
    op.drop_column('trade_in_valuations', 'redemption_method')
    op.create_table('trade_in_decisions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('decision_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('store_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('credit_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trade_in_sessions.id'], name=op.f('trade_in_decisions_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_in_decisions_pkey'))
    )
    op.create_index(op.f('ix_trade_in_decisions_id'), 'trade_in_decisions', ['id'], unique=False)
    # ### end Alembic commands ###
